name = "over-engineer-todo"
main = "./.output/server/index.mjs"
compatibility_date = "2025-07-15"
compatibility_flags = ["nodejs_compat"]

assets = { directory = "./.output/public" }

[vars]
AUTH_FAST_PASSWORD_HASH = "true"

[observability]
[observability.logs]
enabled = false
invocation_logs = true
